apiVersion: v1
kind: Service
annotations:
    argocd-image-updater.argoproj.io/write-back-method: "argocd"
    argocd-image-updater.argoproj.io/image-list: "public.ecr.aws/nginx/nginx:1.23"
    argocd-image-updater.argoproj.io/api.update-strategy: "latest"
metadata:
  name: nginxservice2
  namespace: kataokanamespace9
  labels:
    app: eks-sample-linux-app
spec:
  type: LoadBalancer  # LoadBalancerタイプに設定
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
