apiVersion: v1
kind: Service
annotations:
  argocd-image-updater.argoproj.io/write-back-method: "argocd"
  argocd-image-updater.argoproj.io/image-list: "amazon/amazon-ecs-sample"
  argocd-image-updater.argoproj.io/api.update-strategy: "latest"
metadata:
  name: nginxservice1
  namespace: kataokaap9
  labels:
    app: eks-sample
spec:
  type: LoadBalancer
  selector:
    app: eks-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

