apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample
  template:
    metadata:
      labels:
        app: eks-sample
    spec:
      containers:
      - name: eks-sample-container
        image: amazon/amazon-ecs-sample
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-service1
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: "argocd"  # argocd または git を選択
    argocd-image-updater.argoproj.io/image-list: "public.ecr.aws/nginx/nginx:1.23"  # コンテナイメージの URL
    argocd-image-updater.argoproj.io/api.update-strategy: "latest"  # イメージの更新戦略
spec:
  selector:
    app: eks-sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
