apiVersion: v1
kind: Service
metadata:
  name: nginxservice2
  namespace: kataokanamespace9
  labels:
    app: eks-sample-linux-app
spec:
  type: LoadBalancer  # LoadBalancerタイプに設定
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
