apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample
  template:
    metadata:
      labels:
        app: eks-sample
    spec:
      containers:
      - name: eks-sample-container
        image: amazon/amazon-ecs-sample
        ports:
        - containerPort: 80

