apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment1
  namespace: kataokaap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample
  template:
    metadata:
      labels:
        app: eks-sample
    spec:
      containers:
      - name: eks-sample-container
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - containerPort: 80



