apiVersion: v1
kind: Service
metadata:
  name: nginxservice1
  namespace: kataokaap3
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: "argocd"
    argocd-image-updater.argoproj.io/image-list: "public.ecr.aws/nginx/nginx:1.23"
    argocd-image-updater.argoproj.io/api.update-strategy: "latest"
  labels:
    app: eks-sample
spec:
  type: LoadBalancer
  selector:
    app: eks-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



